<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="HotChocolate.AspNetCore" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" />
    <PackageReference Include="HotChocolate.Data" />
    <PackageReference Include="HotChocolate.Data.MongoDb" />
    <PackageReference Include="HotChocolate.Types" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cineverse.Mongo\Cineverse.Mongo.csproj" />
    <ProjectReference Include="..\Cineverse.Notifications\Cineverse.Notifications.csproj" />
  </ItemGroup>
</Project>
