services:
  cineverse-ui:
    image: cineverse-ui
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - cineverse-network
    restart: always

networks:
  cineverse-network:
    external: true
