<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageVersion Include="Cineverse.Infrastructure.Logging" Version="1.0.0-rc-9" />
    <PackageVersion Include="Cineverse.Infrastructure.Mongo" Version="1.0.1-rc1" />
    <PackageVersion Include="Cineverse.Infrastructure.Mongo.Migrations" Version="1.0.0" />
    <PackageVersion Include="MediatR" Version="14.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageVersion Include="MongoDB.Analyzer" Version="2.0.0" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.11.6" />
  </ItemGroup>
</Project>