apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: cineverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
        - name: identity-api
          image: identity:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7401
          envFrom:
            - configMapRef:
                name: cineverse-config
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: cineverse
spec:
  selector:
    app: identity-api
  ports:
    - port: 7401
      targetPort: 7401
  type: NodePort
