<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Auth\Auth.csproj" />
    <ProjectReference Include="..\IdentityService.Mongo\IdentityService.Mongo.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Cineverse.Infrastructure.Context" />
    <PackageReference Include="Cineverse.Infrastructure.MediatR" />
    <PackageReference Include="Cineverse.Infrastructure.WebApi" />
    <PackageReference Include="Cineverse.NotificationService.Client" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Common\" />
  </ItemGroup>
</Project>
