<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\IdentityService.Mongo\IdentityService.Mongo.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="FluentValidation\" />
    <Folder Include="MediatR\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>
</Project>
