<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\IdentityService.Mongo\IdentityService.Mongo.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="FluentValidation\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Cineverse.Auth" />
    <PackageReference Include="Cineverse.Infrastructure.Context" />
    <PackageReference Include="Cineverse.Infrastructure.MediatR" />
    <PackageReference Include="Cineverse.Infrastructure.WebApi" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
  </ItemGroup>
</Project>
