<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>Cineverse.Infrastructure.Kafka</PackageId>
        <Version>1.0.0-rc-8</Version>
        <Authors>Cineverse Team</Authors>
        <Company>Cineverse</Company>
        <Description>Infrastructure kafka package</Description>
        <RepositoryUrl>https://github.com/DARK6870/Cineverse</RepositoryUrl>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageOutputPath>..\nuget-packages</PackageOutputPath>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Cineverse.Infrastructure.Common" Version="1.0.1-rc-2" />
      <PackageReference Include="Confluent.Kafka" Version="2.12.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.1" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.1" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.1" />
    </ItemGroup>

</Project>
