<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>Cineverse.Infrastructure.Common</PackageId>
        <Version>1.0.1-rc-2</Version>
        <Authors>Cineverse Team</Authors>
        <Company>Cineverse</Company>
        <Description>Infrastructure common package</Description>
        <RepositoryUrl>https://github.com/DARK6870/Cineverse</RepositoryUrl>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageOutputPath>..\nuget-packages</PackageOutputPath>
    </PropertyGroup>

</Project>
