<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Cineverse.Infrastructure.Common" Version="1.0.1-rc-2" />
    <PackageVersion Include="Cineverse.Infrastructure.Kafka" Version="1.0.0-rc-6" />
    <PackageVersion Include="Cineverse.Infrastructure.Logging" Version="1.0.1" />
    <PackageVersion Include="Cineverse.Infrastructure.MediatR" Version="1.0.0-rc-1" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageVersion Include="Hangfire.AspNetCore" Version="1.8.22" />
    <PackageVersion Include="Hangfire.Redis.StackExchange" Version="1.12.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.1" />
    <PackageVersion Include="MongoDB.Analyzer" Version="2.0.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>