<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Cineverse.Infrastructure.Mongo" />
    <PackageReference Include="Cineverse.Infrastructure.Mongo.Migrations" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
