<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Cineverse.Application\Cineverse.Application.csproj" />
      <ProjectReference Include="..\Cineverse.Mongo.Migrations\Cineverse.Mongo.Migrations.csproj" />
    </ItemGroup>

</Project>
