<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\Cineverse.Infrastructure\Cineverse.Infrastructure.csproj" />
      <ProjectReference Include="..\Cineverse.Mongo\Cineverse.Mongo.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation.AspNetCore" />
      <PackageReference Include="MediatR" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="MediatR\Users\Commands\" />
    </ItemGroup>

</Project>
