const REFRESH_TOKEN_KEY = "refresh_token";
const ACCESS_TOKEN_KEY = "access_token";

const REFRESH_TOKEN_LIFETIME_DAYS = 30
const ACCESS_TOKEN_LIFETIME_MINUTES = 30

export {
  REFRESH_TOKEN_KEY,
  ACCESS_TOKEN_KEY,
  REFRESH_TOKEN_LIFETIME_DAYS,
  ACCESS_TOKEN_LIFETIME_MINUTES
}
