<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
    
  <ItemGroup>
    <PackageVersion Include="FluentValidation" Version="12.0.0" />
    <PackageVersion Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageVersion Include="HotChocolate.AspNetCore.Authorization" Version="15.1.10" />
    <PackageVersion Include="HotChocolate.AspNetCore" Version="15.1.10" />
    <PackageVersion Include="HotChocolate.Data" Version="15.1.10" />
    <PackageVersion Include="HotChocolate.Data.MongoDb" Version="15.1.10" />
    <PackageVersion Include="HotChocolate.Types" Version="15.1.10" />
    <PackageVersion Include="MediatR" Version="13.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.18" />
    <PackageVersion Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="9.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.7" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.0" />
    <PackageVersion Include="MongoDB.Analyzer" Version="2.0.0" />
    <PackageVersion Include="MongoDB.Bson" Version="3.4.0" />
    <PackageVersion Include="MongoDB.Driver" Version="3.4.0" />
    <PackageVersion Include="Serilog" Version="4.3.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="Serilog.Enrichers.ClientInfo" Version="2.4.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />
  </ItemGroup>
</Project>