apiVersion: apps/v1
kind: Deployment
metadata:
  name: cineverse-api
  namespace: cineverse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cineverse-api
  template:
    metadata:
      labels:
        app: cineverse-api
    spec:
      containers:
        - name: cineverse-api
          image: myusername/cineverse-api:latest
          ports:
            - containerPort: 80
          env:
            - name: ENV_NAME
              value: "dev"
---
apiVersion: v1
kind: Service
metadata:
  name: cineverse-api
  namespace: cineverse
spec:
  selector:
    app: cineverse-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
